# Generated by Django 3.0.4 on 2020-05-30 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbackmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('feedback', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='resultmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('name', models.CharField(max_length=60)),
                ('fname', models.CharField(default=None, max_length=60)),
                ('mobile', models.BigIntegerField()),
                ('subject', models.CharField(default=None, max_length=100)),
                ('marks', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='scheduletestmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('BCA', 'BCA'), ('BBA', 'BBA'), ('MBA', 'MBA'), ('BTech', 'BTech'), ('Diploma', 'Diploma'), ('BVocational', 'BVocational')], max_length=50)),
                ('subjects', models.CharField(max_length=20)),
                ('date', models.DateField(max_length=20)),
                ('time', models.TimeField()),
                ('duration', models.TimeField()),
                ('questions', models.BigIntegerField()),
                ('marks', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='uploadquestionpapermodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qno', models.BigIntegerField()),
                ('question', models.CharField(max_length=800)),
                ('optiona', models.CharField(max_length=200)),
                ('optionb', models.CharField(max_length=200)),
                ('optionc', models.CharField(max_length=200)),
                ('optiond', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
                ('subject', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='studentdatamodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('BCA', 'BCA'), ('BBA', 'BBA'), ('MBA', 'MBA'), ('BTech', 'BTech'), ('Diploma', 'Diploma'), ('BVocational', 'BVocational')], max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(default=None, max_length=60)),
                ('fname', models.CharField(max_length=60)),
                ('dob', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('General', 'General'), ('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('Minority', 'Minority')], max_length=40)),
                ('qualification', models.CharField(choices=[('10th', '10th'), ('10+2Science', '10+2Science'), ('10+2Commerce', '10+2Commerce'), ('10+2Arts', '10+2Arts')], max_length=40)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(default=None, max_length=100)),
                ('pincode', models.CharField(default=None, max_length=100)),
                ('state', models.CharField(default=None, max_length=100)),
                ('district', models.CharField(default=None, max_length=100)),
                ('source', models.CharField(choices=[('Counsellor', 'Counsellor'), ('Socialmedia', 'Socialmedia'), ('SMS', 'SMS'), ('Leaflet', 'Leaflet'), ('Newspaper', 'Newspaper'), ('Friends/Relatives', 'Friends/Relatives'), ('Poster', 'Poster')], max_length=100)),
                ('counsellor', models.CharField(default=None, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
